// pages/_app.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './custom.css';
import '@fortawesome/fontawesome-free/css/all.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import $ from 'jquery'; // Import jQuery

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Use jQuery here, for example:
  $(document).ready(function () {
    // Your jQuery code goes here
    console.log('Document ready!');
  });

  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
